package hospitalRoom;

import javax.swing.JTextField;
import hospitalRoom.addThreeRoomPatient;
import javax.swing.JOptionPane;

/**
 *
 * @author ShinMinJin
 */
public class hospitalRoom extends javax.swing.JFrame {

    public addSixRoomPatient sR3;
    public addSixRoomPatient sR2;
    public addSixRoomPatient sR1;
    public addThreeRoomPatient tR1;
    public addThreeRoomPatient tR2;
    public addThreeRoomPatient tR3;
    public roomCheck rc1;
    public roomCheck rc2;
    public roomCheck rc3;
    public roomCheck rc4;
    public roomCheck rc5;
    public roomCheck rc6;
    public int coun201 = 0;
    public int coun202 = 0;
    public int coun203 = 0;
    public int coun101 = 0;
    public int coun102 = 0;
    public int coun103 = 0;
    /**
     * Creates new form hospitalRoom
     */
    public hospitalRoom() {
        initComponents();
        rc1 = new roomCheck();
        rc2 = new roomCheck();
        rc3 = new roomCheck();
        rc4 = new roomCheck();
        rc5 = new roomCheck();
        rc6 = new roomCheck();
        sR3 = new addSixRoomPatient(6, 5);
        sR1 = new addSixRoomPatient(6, 4);
        tR1 = new addThreeRoomPatient(3, 1);
        tR2 = new addThreeRoomPatient(3, 2);
        sR2 = new addSixRoomPatient(6, 6);
        tR3 = new addThreeRoomPatient(3, 3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("병실 배정");

        jButton1.setText("101호");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("102호");
        jButton2.setPreferredSize(new java.awt.Dimension(97, 38));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("103호");
        jButton3.setPreferredSize(new java.awt.Dimension(97, 38));
        jButton3.setSize(new java.awt.Dimension(97, 38));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("201호");
        jButton4.setPreferredSize(new java.awt.Dimension(97, 38));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("202호");
        jButton5.setPreferredSize(new java.awt.Dimension(97, 38));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("203호");
        jButton6.setPreferredSize(new java.awt.Dimension(97, 38));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField2)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       if(coun101 == 0) rc1.emptyRoom();
       coun101++;
        int result = JOptionPane.showConfirmDialog(null, "추가하시겠습니까?", "ConFirm", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.CLOSED_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        } else if (result == JOptionPane.YES_OPTION) {
            tR1.threeRoomAdd(1);
            rc1.someRoom();
            JOptionPane.showMessageDialog(null, "남은 인원: " + tR1.pi);
            jTextField1.setText("남은 인원: " + tR1.pi);
            if (tR1.pi.equals("0")) {
                JOptionPane.showMessageDialog(null, "추가할 수 없습니다..");
                rc1.lotRoom();
            }
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange

    }//GEN-LAST:event_jTextField1PropertyChange

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
//        addThreeRoomPatient tR = new addThreeRoomPatient();
//       jTextField1.setText(tR.pi);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if(coun201 == 0) rc1.emptyRoom();
        coun201++;
        int result = JOptionPane.showConfirmDialog(null, "추가하시겠습니까?", "ConFirm", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.CLOSED_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        } else if (result == JOptionPane.YES_OPTION) {
            rc2.someRoom();
            sR1.addSixRoomPatient(1);
            JOptionPane.showMessageDialog(null, "남은 인원: " + sR1.sixpi);
            jTextField2.setText("남은 인원: " + sR1.sixpi);
            if (sR1.sixpi.equals("0")) {
                JOptionPane.showMessageDialog(null, "추가할 수 없습니다..");
                rc2.lotRoom();
            }
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if(coun102 == 0) rc3.emptyRoom();
        coun102++;
        int result = JOptionPane.showConfirmDialog(null, "추가하시겠습니까?", "ConFirm", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.CLOSED_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        } else if (result == JOptionPane.YES_OPTION) {
            rc3.someRoom();
            tR2.threeRoomAdd(1);
            JOptionPane.showMessageDialog(null, "남은 인원: " + tR2.pi);
            jTextField3.setText("남은 인원: " + tR2.pi);
            if (tR2.pi.equals("0")) {
                JOptionPane.showMessageDialog(null, "추가할 수 없습니다..");
                rc3.lotRoom();
            }
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if(coun202 == 0) rc4.emptyRoom();
        coun202++;
        int result = JOptionPane.showConfirmDialog(null, "추가하시겠습니까?", "ConFirm", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.CLOSED_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        } else if (result == JOptionPane.YES_OPTION) {
            rc4.someRoom();
            sR3.addSixRoomPatient(1);

            JOptionPane.showMessageDialog(null, "남은 인원: " + sR3.sixpi);
            jTextField4.setText("남은 인원: " + sR3.sixpi);
            if (sR3.sixpi.equals("0")) {
                JOptionPane.showMessageDialog(null, "추가할 수 없습니다..");
                rc4.lotRoom();
            }
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if(coun103 == 0) rc5.emptyRoom();
        coun103++;
        int result = JOptionPane.showConfirmDialog(null, "추가하시겠습니까?", "ConFirm", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.CLOSED_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        } else if (result == JOptionPane.YES_OPTION) {
            rc5.someRoom();
            tR3.threeRoomAdd(1);
            JOptionPane.showMessageDialog(null, "남은 인원: " + tR3.pi);
            jTextField5.setText("남은 인원: " + tR3.pi);
            if (tR3.pi.equals("0")) {
                JOptionPane.showMessageDialog(null, "추가할 수 없습니다..");
                rc5.lotRoom();
            }
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if(coun103 == 0) rc6.emptyRoom();
        coun103++;
        int result = JOptionPane.showConfirmDialog(null, "추가하시겠습니까?", "ConFirm", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.CLOSED_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        } else if (result == JOptionPane.YES_OPTION) {
            rc6.someRoom();
            sR2.addSixRoomPatient(1);
            JOptionPane.showMessageDialog(null, "남은 인원: " + sR2.sixpi);
            jTextField6.setText("남은 인원: " + sR2.sixpi);
            if (sR2.sixpi.equals("0")) {
                JOptionPane.showMessageDialog(null, "추가할 수 없습니다..");
                rc6.lotRoom();
            }
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "취소합니다.");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hospitalRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hospitalRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hospitalRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hospitalRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hospitalRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
